# Generated by Django 3.1 on 2020-08-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(default=2020)),
                ('color', models.CharField(max_length=255)),
                ('transmission', models.PositiveSmallIntegerField(choices=[(0, 'Ручная'), (1, 'Автомат'), (2, 'Робот')], default=0)),
            ],
        ),
    ]
